apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rp-pods
  labels: 
    app: yellowapp
    env: dev
  namespace: devnamespace
  annotations:
    myecrimage: 503427799577.dkr.ecr.us-east-2.amazonaws.com/dev/myownimage:latest
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchLabels:
      app: yellowapp-pods
  template: 
    metadata:
      name: podlevellables
      labels:
        app: yellowapp-pods
    spec: 
      containers:
        - name: yellowimage
          image: 503427799577.dkr.ecr.us-east-2.amazonaws.com/dev/myownimage:latest
          ports:
            - name: yellowapp-ports
              containerPort: 80
              protocol: TCP
          startupProbe: 
            httpGet:
              path: "/hemanth"
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            exec:
              command:
                - echo hi
          resources:
            requests:
              cpu: 100M
              memory: 200Mi
            limits:
              cpu: 300M
              memory: 300Mi
           



    